service: decidim_hassig
image: hhassig/decidim-hassig
deploy_timeout: 120
servers:
  web:
    - 5.78.45.115
proxy:
  ssl: true
  host: decidim.hassig.com
  app_port: 3000
  healthcheck:
    path: "/kamal-health"
    interval: 15
    timeout: 180
registry:
  username: hhassig
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - KAMAL_REGISTRY_PASSWORD
    - ENCRYPTION_KEY
  clear:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
    SOLID_QUEUE_IN_PUMA: true
    DECIDIM_API_DISCLOSE_SYSTEM_VERSION: true
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
volumes:
  - "decidim_hassig_storage:/app/storage"
asset_path: /app/public
builder:
  arch: amd64
  args:
    SECRET_KEY_BASE: "<%= `rails secret`.strip %>"
    RAILS_MASTER_KEY: "<%= File.read('config/credentials/production.key').strip rescue File.read('config/master.key').strip %>"
accessories:
  db:
    image: postgres:16
    host: 5.78.45.115
    port: "127.0.0.1:5439:5432"
    env:
      secret:
        - POSTGRES_PASSWORD
      clear:
        POSTGRES_USER: decidim_hassig
        POSTGRES_DB: decidim_hassig_production
    volumes:
      - /srv/decidim_hassig/postgres-data:/var/lib/postgresql/data
